
POST http://127.0.0.1:8000/languages
Content-Type: application/json

{
    "name": "Python",
    "type": "Interpreted",
    "authors": [
        {"name": "Lele", "section": "Chatpter 1"},
        {"name": "Mpho", "section": "Foreword"}
    ]
}

###
GET http://127.0.0.1:8000/languages

###
GET http://127.0.0.1:8000/language/3

###
PUT http://127.0.0.1:8000/language/1
Content-Type: application/json

{
    "name": "Python",
    "type": "Interpreted",
    "date_released": "2025-02-25",
    "authors": [
        {
        "name": "Johannes",
        "section": "Full Document"
        }
    ]
}

###
DELETE http://127.0.0.1:8000/language/3