"""added date_released field to Language model

Revision ID: 75f221161435
Revises: 04f840fea4b9
Create Date: 2026-09-14 23:04:44.524588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '75f221161435'
down_revision: Union[str, Sequence[str], None] = '04f840fea4b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language', sa.Column('date_released', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language', 'date_released')
    # ### end Alembic commands ###
